# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CodingChallenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CodingChallenge
  pod 'Alamofire' , '~> 5.0.0-rc.1'
  pod 'RxSwift', '~> 4.0'
  pod 'RxDataSources', '~> 3.0'
  pod 'RxCocoa', '~> 4.0'
  pod 'RxSwiftExt', '~> 3.0'
  
  pod 'SBAProgressHud', '~> 1.3'
  pod 'Kingfisher', '~> 5.7.1'
  
  target 'CodingChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CodingChallengeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
